// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SaniatsCakeShop.Models;

namespace SaniatsCakeShop.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220823153224_1827898")]
    partial class _1827898
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClaimType = "http://schemas.microsoft.com/ws/2008/06/identity/claims/role",
                            ClaimValue = "Administrator",
                            UserId = "a097afec-61a7-4372-b405-de00c4dd41ff"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("SaniatsCakeShop.Models.Cake", b =>
                {
                    b.Property<int>("CakeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AllergyInformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Calorie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ImageThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InStock")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCakeOfTheWeek")
                        .HasColumnType("bit");

                    b.Property<string>("LongDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NutritionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Protein")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fiber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("magnesium")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("niacin")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CakeId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Cakes");

                    b.HasData(
                        new
                        {
                            CakeId = 1,
                            AllergyInformation = "",
                            Calorie = "352 calories",
                            CategoryId = 1,
                            ImageThumbnailUrl = "https://i.imgur.com/lbEcaUo.jpeg",
                            ImageUrl = "https://i.ytimg.com/vi/dh6GgbgQ5j0/maxresdefault.jpg",
                            InStock = true,
                            IsCakeOfTheWeek = true,
                            LongDescription = "A delicious soft and light vanilla sponge cake filled with homemade fruit filling and topped with delicious fresh fruits and freshly whipped cream.",
                            Name = "FRESH FRUIT CAKE",
                            NutritionName = "Nutrition Info : Per 100 grams",
                            Price = 8.95m,
                            Protein = "0.72 grams",
                            ShortDescription = " ",
                            fiber = " 0.24 grams",
                            magnesium = "0.34 grams ",
                            niacin = " 0.14 grams"
                        },
                        new
                        {
                            CakeId = 2,
                            AllergyInformation = "",
                            Calorie = "97 calories",
                            CategoryId = 1,
                            ImageThumbnailUrl = "https://i.imgur.com/pSpITQh.jpeg",
                            ImageUrl = "https://jennakateathome.com/wp-content/uploads/2022/02/fresh-fruit-cake-27-1.jpg",
                            InStock = true,
                            IsCakeOfTheWeek = false,
                            LongDescription = "Baking a delicious (and pretty!) cake from scratch doesn't need to be complicated. With a few staple pantry ingredients, some whipped cream and your favorite fresh fruits, you can make a delicious cake that the entire family will enjoy.",
                            Name = "Fresh Berry Cream Cake",
                            NutritionName = "Nutrition Info : Per 100 grams",
                            Price = 18.95m,
                            Protein = "0.72 grams",
                            ShortDescription = " ",
                            fiber = " 0.24 grams",
                            magnesium = "30.4 grams ",
                            niacin = " 0.24 grams"
                        },
                        new
                        {
                            CakeId = 3,
                            AllergyInformation = "",
                            Calorie = "3513 calories",
                            CategoryId = 5,
                            ImageThumbnailUrl = "https://i.imgur.com/cHoyUc4.jpeg",
                            ImageUrl = "https://amaribakery.files.wordpress.com/2018/06/fraisier-cake.jpg",
                            InStock = true,
                            IsCakeOfTheWeek = false,
                            LongDescription = "This type of sponge cake is made with whole eggs(no separation); this technique is a bit more involved as opposed to the Biscuit.Eggs are mixed with sugar and heated over simmering water then whipped. You must ensure that you constantly whip the egg mixture so the eggs don’t cook and become scrambled eggs. Make sure the bowl you’re mixing in doesn’t come into contact with the water in the pot below.The pot of water should not come to a boil; it should simmer.Whisk the egg mixture on top of the water about 3 to 5 minutes; until the bowl is warm to the touch or until it gets to about 110°-120°F / 43°-49°C.Whipping the eggs over heat allows them to whip to a greater volume.After the eggs and sugar have doubled or almost tripled in volume; add some melted butter and fold gently – then add the flour and fold. The eggs are used as the raising agents; this is why you need them to double or triple in volume.",
                            Name = "Fraisier cake",
                            NutritionName = "Nutrition Info : Per 100 grams",
                            Price = 11.95m,
                            Protein = "0.97 grams",
                            ShortDescription = "",
                            fiber = " 0.42 grams",
                            magnesium = "0.234 grams ",
                            niacin = " 0.44 grams"
                        },
                        new
                        {
                            CakeId = 4,
                            AllergyInformation = "",
                            Calorie = "523 calories",
                            CategoryId = 4,
                            ImageThumbnailUrl = "https://i.imgur.com/Hq2Wkjw.jpeg",
                            ImageUrl = "https://www.breadtalk.com.sg/wp-content/uploads/2020/07/Hersheys-Love-scaled.jpg",
                            InStock = true,
                            IsCakeOfTheWeek = false,
                            LongDescription = "This type of sponge cake contains both the egg white and yolks in the recipe. They are however first separated; whipped separately (egg whites and sugar to make a meringue) then mixed back together. In this type of Sponge cake; the eggs are the raising agent in the recipe. Chemical raising agents are not used in this recipe traditionally",
                            Name = "Biscuit",
                            NutritionName = "Nutrition Info : Per 100 grams",
                            Price = 11.95m,
                            Protein = "0.72 grams",
                            ShortDescription = "",
                            fiber = " 0.44 grams",
                            magnesium = "0.64 grams ",
                            niacin = " 0.14 grams"
                        },
                        new
                        {
                            CakeId = 5,
                            AllergyInformation = "",
                            Calorie = "352 calories",
                            CategoryId = 8,
                            ImageThumbnailUrl = "https://i.imgur.com/zQWRNN0.jpeg",
                            ImageUrl = "https://amaribakery.files.wordpress.com/2018/06/vanilla-slice-plain-of-chiffon-by-amari.png?w=446&h=446",
                            InStock = true,
                            IsCakeOfTheWeek = false,
                            LongDescription = "This sponge cake contains both a fat and a chemical raising agent; oil and baking powder, in the ingredients list. The eggs are also separated; the whites are beaten until stiff. All the other ingredients are combined in another bowl to make a smooth batter like a pancake batter; the beaten egg whites are then folded into the ‘pancake’ batter.  The result after this mixing process is of a lighter sponge cake texture, but with a rich flavor like butter/oil cakes. These cakes are generally layered and filled with fillings and frostings. They don’t always require decoration especially when used in Chiffon cake pans or Bundt pans; you can just dust some icing sugar on top or drizzle a little bit of glaze. You can however decorate with whipped cream or meringue butter-creams if you prefer.",
                            Name = "Chiffon cakes by Amari",
                            NutritionName = "Nutrition Info : Per 100 grams",
                            Price = 13.95m,
                            Protein = "0.17 grams",
                            ShortDescription = "",
                            fiber = " 0.24 grams",
                            magnesium = "0.24 grams ",
                            niacin = " 0.14 grams"
                        },
                        new
                        {
                            CakeId = 6,
                            AllergyInformation = "",
                            Calorie = "351 calories",
                            CategoryId = 7,
                            ImageThumbnailUrl = "https://i.imgur.com/8OCaqUk.jpeg",
                            ImageUrl = "https://www.kingarthurbaking.com/sites/default/files/styles/featured_image/public/recipe_legacy/4179-3-large.jpg?itok=dphbBuMQ",
                            InStock = true,
                            IsCakeOfTheWeek = false,
                            LongDescription = "This flourless cake, featuring both chocolate and cocoa, is rich, rich, RICH! A thick icing of chocolate ganache glaze takes it over the top. Depending on how you observe Passover, this cake can make a great addition to your Seder since it contains neither flour nor leavening; and of course, it's also ideal for those looking to avoid gluten.",
                            Name = "Flourless Chocolate Cake",
                            NutritionName = "Nutrition Info : Per 100 grams",
                            Price = 17.95m,
                            Protein = "0.72 grams",
                            ShortDescription = "",
                            fiber = " 0.42 grams",
                            magnesium = "0.24 grams ",
                            niacin = " 0.41 grams"
                        },
                        new
                        {
                            CakeId = 7,
                            AllergyInformation = "",
                            Calorie = "352 calories",
                            CategoryId = 7,
                            ImageThumbnailUrl = "https://i.imgur.com/0QocoJX.jpeg",
                            ImageUrl = "https://d3lp4xedbqa8a5.cloudfront.net/s3/digital-cougar-assets/Gt/2018/05/23/15958/GT1805_Grains_Fennel_spiced_semolina_cake_with_yoghurtA.jpg?width=922&height=768&mode=crop&anchor=topcenter&quality=75",
                            InStock = false,
                            IsCakeOfTheWeek = false,
                            LongDescription = "This combination of citrus, sugar and spice makes for an unbeatable afternoon-tea treat.",
                            Name = "Fennel-spiced semolina cake with yoghurt",
                            NutritionName = "Nutrition Info : Per 100 grams",
                            Price = 11.95m,
                            Protein = "0.72 grams",
                            ShortDescription = "",
                            fiber = " 0.34 grams",
                            magnesium = "0.4 grams ",
                            niacin = " 0.14 grams"
                        },
                        new
                        {
                            CakeId = 8,
                            AllergyInformation = "",
                            Calorie = "3225 calories",
                            CategoryId = 7,
                            ImageThumbnailUrl = "https://i.imgur.com/nbXFNdC.jpeg",
                            ImageUrl = "https://d3lp4xedbqa8a5.cloudfront.net/s3/digital-cougar-assets/Gt/2018/07/03/15967/chocolate-coconut-date-slab.jpg?width=922&height=768&mode=crop&anchor=topcenter&quality=75",
                            InStock = true,
                            IsCakeOfTheWeek = true,
                            LongDescription = "A layer of coconut ganache over this fudgy slab keeps it rich and creamy, but dairy-free, while raw cacoa and dates steer it firmly away from corner-store chocolate bar territory.",
                            Name = "Chocolate, coconut and date slab",
                            NutritionName = "Nutrition Info : Per 100 grams",
                            Price = 12.95m,
                            Protein = "0.71 grams",
                            ShortDescription = "",
                            fiber = " 0.42 grams",
                            magnesium = "0.41 grams ",
                            niacin = " 0.42 grams"
                        },
                        new
                        {
                            CakeId = 9,
                            AllergyInformation = "",
                            Calorie = "3521 calories",
                            CategoryId = 3,
                            ImageThumbnailUrl = "https://i.imgur.com/bRx0mVn.jpg",
                            ImageUrl = "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F24%2F1970%2F01%2F2341302_butte_054_2_0_1.jpg",
                            InStock = true,
                            IsCakeOfTheWeek = true,
                            LongDescription = "We took the traditional pound cake recipe and gave it a stunning, triple-chocolate twist. This cake means business. A duo of glazes—one creamy chocolate, the other subtle buttermilk—comes together atop this dreamy confection. It's indulgent and, we admit, so much fun to eat and serve. Chocolate enthusiasts will be over the moon for this recipe, but it has enough unexpected flavor—thanks to the addition of the buttermilk glaze—that you'll also win over the harder-to-please dessert eaters at the table. Warning: You—and they—won't be able to resist a second slice.",
                            Name = "Triple-Chocolate Buttermilk Pound Cake",
                            NutritionName = "Nutrition Info : Per 100 grams",
                            Price = 15.95m,
                            Protein = "0.72 grams",
                            ShortDescription = "",
                            fiber = " 0.42 grams",
                            magnesium = "0.41 grams ",
                            niacin = " 0.43 grams"
                        },
                        new
                        {
                            CakeId = 10,
                            AllergyInformation = "",
                            Calorie = "351 calories",
                            CategoryId = 3,
                            ImageThumbnailUrl = "https://i.imgur.com/dWW8B1n.jpeg",
                            ImageUrl = "https://www.pauladeenmagazine.com/wp-content/uploads/2019/04/p2.jpg",
                            InStock = true,
                            IsCakeOfTheWeek = false,
                            LongDescription = "Cream cheese, buttermilk, and strawberry glaze team up to create a delicious pound cake",
                            Name = "Strawberry Swirl Pound Cake",
                            NutritionName = "Nutrition Info : Per 100 grams",
                            Price = 15.95m,
                            Protein = "0.73 grams",
                            ShortDescription = "",
                            fiber = " 0.45 grams",
                            magnesium = "0.44 grams ",
                            niacin = " 0.42 grams"
                        },
                        new
                        {
                            CakeId = 11,
                            AllergyInformation = "",
                            Calorie = "3524 calories",
                            CategoryId = 4,
                            ImageThumbnailUrl = "https://i.imgur.com/cNEGnwd.jpeg",
                            ImageUrl = "https://projectveganbaking.com/wp-content/uploads/2020/06/IMG_6434_Fotor-copy.jpg",
                            InStock = false,
                            IsCakeOfTheWeek = false,
                            LongDescription = "Joconde is a light and airy sponge cake that you can use to make many types of desserts. Joconde does not have a lot of fat in it and is considered to be a healthy version of a traditional cake. ",
                            Name = "Joconde cake",
                            NutritionName = "Nutrition Info : Per 100 grams",
                            Price = 1.95m,
                            Protein = "0.237 grams",
                            ShortDescription = "",
                            fiber = " 0.344 grams",
                            magnesium = "0.24 grams ",
                            niacin = " 0.444 grams"
                        });
                });

            modelBuilder.Entity("SaniatsCakeShop.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Fruit cakes"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Pound cakes"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Sponge cakes"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Genoise cakes"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Baked Flourless cakes"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Chiffon  cakes"
                        });
                });

            modelBuilder.Entity("SaniatsCakeShop.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("OrderPlaced")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("OrderTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("State")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("SaniatsCakeShop.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("CakeId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("CakeId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("SaniatsCakeShop.Models.ShoppingCartItem", b =>
                {
                    b.Property<int>("ShoppingCartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int?>("CakeId")
                        .HasColumnType("int");

                    b.Property<string>("ShoppingCartId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ShoppingCartItemId");

                    b.HasIndex("CakeId");

                    b.ToTable("ShoppingCartItems");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SaniatsCakeShop.Models.Cake", b =>
                {
                    b.HasOne("SaniatsCakeShop.Models.Category", "Category")
                        .WithMany("Cakes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SaniatsCakeShop.Models.OrderDetail", b =>
                {
                    b.HasOne("SaniatsCakeShop.Models.Cake", "Cake")
                        .WithMany()
                        .HasForeignKey("CakeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SaniatsCakeShop.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cake");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("SaniatsCakeShop.Models.ShoppingCartItem", b =>
                {
                    b.HasOne("SaniatsCakeShop.Models.Cake", "Cake")
                        .WithMany()
                        .HasForeignKey("CakeId");

                    b.Navigation("Cake");
                });

            modelBuilder.Entity("SaniatsCakeShop.Models.Category", b =>
                {
                    b.Navigation("Cakes");
                });

            modelBuilder.Entity("SaniatsCakeShop.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
